### ISSUE TITLE
How to get PyCharm test run working with pytest-dotenv?

### ISSUE THREAD

**Issue by namgivu** [quiqua/pytest-dotenv#10]
I succeeded with [running my test with pytest-dotenv](https://github.com/namgivu/pytest-start/commit/1fc0e1acc3b375da0089d2f41b6fa47801690f8a) from command line as below quote
```
============================= test session starts ==============================
platform linux -- Python 3.6.9, pytest-5.2.2, py-1.8.0, pluggy-0.13.0
rootdir: /my/local/path/to/pytest-start, inifile: pytest.ini
plugins: forked-1.1.3, dotenv-0.4.0, xdist-1.30.0
collected 1 item

tests/test_dotenv.py .

============================== 1 passed in 0.01s ===============================
```

Though when running the test with PyCharm test run mode, the plugin not working. 
So my question is how to get PyCharm test run working with pytest-dotenv?

**Comment by quiqua** [comment]
I've never tried to use PyCharm and don't know how it will interact with pytest and its plugins in general.

Do you have a sample project I could look into?

**Comment by namgivu** [comment]
> Do you have a sample project I could look into?

Yeah sure, here it is https://github.com/namgivu/pytest-start - we can just git clone then open this repo with [PyCharm edition Community](https://www.jetbrains.com/pycharm/download/)

**Comment by quiqua** [comment]
Please have a look at the PR I opened at your [repo](https://github.com/namgivu/pytest-start/pull/1). The noteworthy change is using the virtualenv you installed pytest and pytest-dotenv.
