### ISSUE TITLE
Environment variables are not found when pytest is started in shell

### ISSUE THREAD

**Issue by lgrosser-tiplu** [quiqua/pytest-dotenv#11]
Hi,
I am using Pycharm 2019.3.1, the package works great when I start pytest by using right-click on the respective test folder from within Pycharm, all environment variables are found and used. However, if I start pytest from the console, the variables are not found. Am I missing a cli parameter that tells pytest to use pytest-dotenv?

**Comment by quiqua** [comment]
If you use pytest from the console, do you use a virtualenv and did you install pytest-dotenv to that virtualenv?

You can run `pip freeze` from the console to see which packages are available to you / have been installed to the current python executable.

**Comment by lgrosser-tiplu** [comment]
I am using virtualenv and installed `pytest-dotenv==0.4.0` to the virtual environment from within I am starting the shell commando.

**Comment by quiqua** [comment]
Can you provide an example project to replicate this and help you out?

**Comment by lgrosser-tiplu** [comment]
I just solved it. My pytest.ini and .env file was not in the root directory of the repository. Thank you for this useful plugin

**Comment by untidy-hair** [comment]
It's good to mention that you can specify `dirname/your.env` in .ini file, too.
