### ISSUE TITLE
Add ability to pass as argument

### ISSUE THREAD

**Issue by Amertz08** [quiqua/pytest-dotenv#12]
It would be nice to be able to pass `--env-file` or something similar as a CLI option. I switch stuff like databases off `.env` files and would like to avoid maintaining a 1-to-1 of `pytest.ini` files and `.env` files. Avoids `pytest-dev.ini -> dev.env`, `pytest-qa.ini -> qa.env` and `pytest-prod.ini -> prod.env`.

**Comment by quiqua** [comment]
I'll have a look into this in the next weeks.

If you want to open a PR yourself, take a look at [the pep8 plugin](https://bitbucket.org/pytest-dev/pytest-pep8/src/default/pytest_pep8.py) to add a command line option.

**Comment by quiqua** [comment]
This has been fixed with #15

**Comment by Amertz08** [comment]
Thanks for doing this. I am already using it to test my app locally against local infrastructure as well as dev infra. One thought might be some type of warning or even failure if the file cannot be found.

**Comment by quiqua** [comment]
> One thought might be some type of warning or even failure if the file cannot be found.

Feel free to open up a PR with the required changes :)
