### ISSUE TITLE
Entrypoint collides with other pytest plugins

### ISSUE THREAD

**Issue by desolat** [quiqua/pytest-dotenv#13]
The pytest `entry_point` used for pytest-dotenv is named "env" and thus does collide with other pytest plugins e.g. [pytest-env](https://github.com/MobileDynasty/pytest-env). Thus only one of these plugins can be installed and used. 

I'd suggest using the specific plugin name "dotenv" for the pytest `entry_point`. This is also suggested in the [pytest documentation](https://docs.pytest.org/en/latest/writing_plugins.html#making-your-plugin-installable-by-others).

**Comment by quiqua** [comment]
A new version 0.5.1 has been uploaded :)
