### ISSUE TITLE
Use `.env` as default?

### ISSUE THREAD

**Issue by wcooley** [quiqua/pytest-dotenv#3]
This looks like a great little plug-in that will save me from having to remember to prefix my pytest/tox commands with `dotenv-run` to load my `.env` file for testing. Would you be amenable to using `.env` as the default, so the plugin can be used without additional configuration? It's the default used in *python-dotenv* itself and seems to be largely the default for most things I've seen using this sort of thing.

**Comment by quiqua** [comment]
This plug-in does not create a `pytest.ini` file, when it is installed, you must do that yourself to configure pytest to your needs.

Further information on how to configure pytest can be found here : https://docs.pytest.org/en/latest/customize.html#initialization-determining-rootdir-and-inifile

I will sleep on it though.
What should be the desired behaviour when both files `.env` and `pytest.ini` are present and `pytest.ini` referes to different env-files such as `.env.test`?
Should `.env` be a fallback?

**Comment by wcooley** [comment]
Perhaps I've not caught this in the README, but are you implying the `pytest.ini` itself can contain environment variables? I was under the impression that `pytest.ini` is only used to configure `env_files` and `env_override_existing_values`?

Or perhaps my request was poorly phrased? How about this: "In absence of `env_files` being configured in `pytest.ini` (or wherever), behave as if it were configured with `env_files = ./.env`."?

One of the practical benefits of "convention over configuration" is reduction of unnecessary "stuff", so having a default that is the same as other tools means less "stuff" to maintain -- you'd be surprised how a couple of lines here and there can add up.

BTW, why does the documentation use `./.env` instead of just `.env`? These are usually the same; does the prepended `./` anchor it to the pytest rootdir?

**Comment by quiqua** [comment]
>  are you implying the pytest.ini itself can contain environment variables

No, sorry if it sounded that way.

> why does the documentation use ./.env instead of just .env?

Yes, thats the same, I just like that notation to make it clear for myself.

Would you mind to open up a PR for this issue?

**Comment by frob** [comment]
I opened a PR with this suggestion.

**Comment by quiqua** [comment]
I'll leave that issue open until the next release, probably by the end of the week.

**Comment by quiqua** [comment]
Closed via #9 and 468d74f
